config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders, only: [:index, :show]
  resources :accounts, only: [:index, :show]

  root :to => redirect('/orders')
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :rememberable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account, only: [:show]

  def index
    @accounts = Account.all
  end

  def show
  end

  private
    def set_account
      @account = Account.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show]

  def index
    @orders = Order.all
  end

  def show
  end


  private
    def set_order
      @order = Order.find(params[:id])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/accounts/index.html.erb
<div class="row">
  <div class="col">
    <p id="notice"><%= notice %></p>
  </div>
  <div class="col">
    <h1>Accounts</h1>
  </div>
  <div class="col">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th># Orders</th>
          <th colspan="1"></th>
        </tr>
      </thead>
      <tbody>
        <% @accounts.each do |account| %>
          <tr>
            <td><%= account.name %></td>
            <td><%= account.orders.count %></td>
            <td><%= link_to 'Show', account %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdvancedQueriesWithActiveRecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link rel="stylesheet" href="https://unpkg.com/mustard-ui@latest/dist/css/mustard-ui.min.css">
  </head>

  <body>
    <div class="container-large">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<div class="row">
  <div class="col">
    <p id="notice"><%= notice %></p>
  </div>
  <div class="col">
    <h1>Orders</h1>
  </div>
  <div class="col">
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Amount</th>
          <th>Status</th>
          <th>Account</th>
          <th colspan="1"></th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= order.date %></td>
            <td><%= number_to_currency order.amount %></td>
            <td><%= order.status %></td>
            <td>
              <%= link_to order.account.name, order.account %>
            </td>
            <td><%= link_to 'Show', order %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/show.html.erb
<div class="row">
  <div class="col">
    <p id="notice"><%= notice %></p>
  </div>
  <div class="col">
    <p>
      <strong>Date:</strong>
      <%= @order.date %>
    </p>
  </div>
  <div class="col">
    <p>
      <strong>Amount:</strong>
      <%= number_to_currency @order.amount %>
    </p>
  </div>
  <div class="col">
    <p>
      <strong>Status:</strong>
      <%= @order.status %>
    </p>
  </div>
  <div class="col">
    <p>
      <strong>Account:</strong>
      <%= link_to @order.account.name, @order.account %>
    </p>
  </div>
  <div class="col">
    <%= link_to 'All Orders', orders_path %>
  </div>
</div>